
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    dashboard-camera:
      mode: yaml
      filename: dashboards/camera.yaml
      title: Cameras
      icon: mdi:cctv
      show_in_sidebar: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.68.0/24

shell_command:
  git_pull: /config/scripts/git_pull.sh

